name: Auto-format Code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g prettier
          yarn install

      - name: Set Git user
        run: |
          git config --global user.email "benedictgabriel73@gmail.com"
          git config --global user.name "Benhexie"

      - name: Format JavaScript/TypeScript files
        run: |
          prettier --write "**/*.js" "**/*.jsx" "**/*.ts" "**/*.tsx" || true

      - name: Format CSS files
        run: |
          prettier --write "**/*.css" "**/*.scss" "**/*.sass" "**/*.less" || true

      - name: Format JSON files
        run: |
          prettier --write "**/*.json" || true

      - name: Format Markdown files
        run: |
          prettier --write "**/*.md" || true

      - name: Commit formatted files
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-format code" && git push origin HEAD:main
